apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fitness-platform
data:
  EUREKA_URL: http://eureka-service:8761/eureka/
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  MONGODB_URI: mongodb://mongodb-service:27017
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
