server:
  port: 8082

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ===============================
# JWT Configuration
# ===============================
jwt:
  secret: ${JWT_SECRET:fitness-microservice-jwt-secret-key-which-is-long-enough-for-hmac-sha256}
  access-expiration: 900000
  refresh-expiration: 604800000

# ===============================
# Actuator Configuration
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  metrics:
    tags:
      application: auth-service
