input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [message] {
    json {
      source => "message"
      target => "parsed"
    }
  }

  mutate {
    add_field => {
      "service_name" => "%{[parsed][spring.application.name]}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "fitness-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
